name: Automatic Event Date Updater

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      branch:
        description: "Run tests on branch"
        required: true
        default: "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Message
        run: echo "Workflow triggered at $(date)"

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread
          pip install pandas
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python Script
        run: |
          python_script="script_2.py"
          python "$python_script" > eventData.ts
      
      - name: Move File to Workspace
        run: mv eventData.ts $GITHUB_WORKSPACE/eventData.ts
